spring:
  profiles:
    active: alpha
---
server:
  servlet:
    context-path: /admin
  port: 8088
spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://182.61.60.156:3306/springboot_project?serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: user22
    password: Abc123456+
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /storage/**
  resources:
    static-locations: file:e:/storage/
  jackson:
    default-property-inclusion: non_null
